"""Applies Ayah's Android config to the folder generated by `flutter create`.

Idempotent: safe to run more than once. Used by CI and usable locally:
    python3 tool/ci/patch_android.py
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "android/app/src/main/AndroidManifest.xml"
RES_XML = ROOT / "android/app/src/main/res/xml/network_security_config.xml"
GRADLE_KTS = ROOT / "android/app/build.gradle.kts"
GRADLE_GROOVY = ROOT / "android/app/build.gradle"

PERMISSIONS = """
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>"""

RECEIVERS = """
        <receiver android:exported="false"
            android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />
        <receiver android:exported="false"
            android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED"/>
                <action android:name="android.intent.action.QUICKBOOT_POWERON"/>
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
            </intent-filter>
        </receiver>"""

NETWORK_CONFIG = """<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">127.0.0.1</domain>
    </domain-config>
</network-security-config>
"""

DESUGAR_LIB = "com.android.tools:desugar_jdk_libs:2.1.4"


def patch_manifest() -> None:
    text = MANIFEST.read_text(encoding="utf-8")
    if "POST_NOTIFICATIONS" not in text:
        text = re.sub(r"(<manifest[^>]*>)", r"\1" + PERMISSIONS, text, count=1)
    if "networkSecurityConfig" not in text:
        text = text.replace(
            "<application",
            '<application\n        android:networkSecurityConfig="@xml/network_security_config"',
            1,
        )
    text = re.sub(r'android:label="[^"]*"', 'android:label="Ayah"', text, count=1)
    if "ScheduledNotificationReceiver" not in text:
        text = re.sub(r"(<application[^>]*>)", r"\1" + RECEIVERS, text, count=1)
    MANIFEST.write_text(text, encoding="utf-8")
    RES_XML.parent.mkdir(parents=True, exist_ok=True)
    RES_XML.write_text(NETWORK_CONFIG, encoding="utf-8")


def patch_gradle() -> None:
    if GRADLE_KTS.exists():
        path, flag, dep = (
            GRADLE_KTS,
            "isCoreLibraryDesugaringEnabled = true",
            f'dependencies {{\n    coreLibraryDesugaring("{DESUGAR_LIB}")\n}}\n',
        )
    elif GRADLE_GROOVY.exists():
        path, flag, dep = (
            GRADLE_GROOVY,
            "coreLibraryDesugaringEnabled true",
            f"dependencies {{\n    coreLibraryDesugaring '{DESUGAR_LIB}'\n}}\n",
        )
    else:
        sys.exit("No android/app/build.gradle(.kts) found — run `flutter create .` first.")

    text = path.read_text(encoding="utf-8")
    if "CoreLibraryDesugaringEnabled" not in text and "coreLibraryDesugaringEnabled" not in text:
        if "compileOptions {" in text:
            text = text.replace("compileOptions {", "compileOptions {\n        " + flag, 1)
        else:
            text = re.sub(r"(android\s*\{)", r"\1\n    compileOptions {\n        " + flag + "\n    }", text, count=1)
    if "desugar_jdk_libs" not in text:
        text = text.rstrip() + "\n\n" + dep
    path.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    patch_manifest()
    patch_gradle()
    print("Android config patched.")
